pricing: 1000
back_service1:
  login:
    username_demo: user1
    password_demo: password1
    url: https://www.abc.com/token/auth
source: application.yaml
logging:
  level:
    root: DEBUG
aws:
  region: ap-southeast-2
  kms:
    keyId: arn:aws:kms:ap-southeast-2:155347622759:key/812d7887-eebc-4194-b2b9-4b40cd6a3efa
